apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd

resources:
- namespace.yaml

- webhook-issuer.certificate.yaml
- webhook-issuer.issuer.yaml
- jaeger-injector.certificate.yaml
- jaeger-injector.helm-release.yaml

