apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: wac-hospital

secretGenerator:
  - name: repository-pat
    namespace: wac-hospital
    type: Opaque
    envs:
      - params/repository-pat.env
    options:
        disableNameSuffixHash: true
  - name: mongodb-auth
    namespace: wac-hospital
    type: Opaque
    envs:
      - params/mongodb-auth.env
    options:
        disableNameSuffixHash: true
  - name: oidc-client
    namespace: wac-hospital
    type: Opaque
    envs:
      - params/oidc-client.env
    options:
        disableNameSuffixHash: true
  - name: linkerd-trust-anchor
    namespace: linkerd
    type: kubernetes.io/tls
    options:
        disableNameSuffixHash: true
    files:
    - tls.crt=params/linkerd-ca.crt
    - tls.key=params/linkerd-ca.key
