apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: milung/ambulance-wl-webapi
  newName: milung/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20231130.1502 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
- name: milung/ambulance-ufe
  newName: milung/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20231120.1356 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.2 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
