apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: linkerd-viz
spec:
  parentRefs:
    - name: wac-hospital-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /viz
      backendRefs:
        - group: ""
          kind: Service
          name: http-echo
          #namespace: linkerd-viz
          port: 80