apiVersion: apps/v1
kind: Deployment
metadata:
  name: milung-ambulance-webapi 
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /milung-openapi
            - name: BASE_URL
              value: /milung-openapi-ui