apiVersion: apps/v1
kind: Deployment
metadata:
  name: ufe-controller
spec:
  template: 
    metadata:
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: ufe-controller
        env:
          - name: BASE_URL
            value: /ui/