apiVersion: apps/v1
kind: Deployment
metadata:
  name: ufe-controller
  annotations:
    linkerd.io/inject: disabled
spec:
  template: 
    spec:
      containers:
      - name: ufe-controller
        env:
          - name: BASE_URL
            value: /ui/