kind: Service
apiVersion: v1
metadata:
  name: milung-openapi-ui
spec:  
  selector:
    pod: milung-ambulance-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80  
    targetPort: 8081