apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd-viz

resources:
- namespace.yaml
- webhook-issuer.certificate.yaml
- webhook-issuer.issuer.yaml
- tap.certificate.yaml
- viz.certificate.yaml
- helm-release.yaml
- linkerd-viz.http-route.yaml

