apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
spec:
  interval: 1m
  dependsOn:  
  - name: linkerd-control-plane
    namespace: linkerd
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 1m
      reconcileStrategy: Revision
  values:
    prometheusUrl: http://prometheus-server.wac-hospital
    jaegerUrl: http://jaeger-collector.wac-hospital
    tap:
      externalSecret: true
      injectCaFrom: webhook-issuer-tls
    tapInjector:
      externalSecret: true
      injectCaFrom: webhook-issuer-tls

