apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 1m
  dependsOn: 
  - name: linkerd-crds
  chart:
    spec:
      chart: linkerd-control-plane
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 1m
      reconcileStrategy: Revision
  values:
    proxy: 
      logLevel: warn,linkerd=debug,trust_dns=error
    proxyInit:
      # docker container runtime, 
      # see https://linkerd.io/2.14/tasks/troubleshooting/#l5d-proxy-init-run-as-root
      runAsRoot: true

    prometheusUrl: http://prometheus-server.wac-hospital
    identity:
      issuer:
        scheme: kubernetes.io/tls
    policyValidator: 
      externalSecret: true 
      injectCaFrom: linkerd/webhook-issuer-tls
    proxyInjector:
      externalSecret: true
      injectCaFrom: linkerd/webhook-issuer-tls
    profileValidator:
      externalSecret: true 
      injectCaFrom: linkerd/webhook-issuer-tls
  valuesFrom:
    # identity trust anchor certificate (shared accross clusters)
  - kind: Secret
    name: linkerd-trust-anchor
    valuesKey: tls.crt
    targetPath: identityTrustAnchorsPEM
  



