apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 1m
  dependsOn: 
  - name: linkerd-crds
  chart:
    spec:
      chart: linkerd-control-plane
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 1m
      reconcileStrategy: Revision
  values:
    prometheusUrl: http://prometheus-server.wac-hospital
    identity:
      issuer:
        scheme: kubernetes.io/tls
    policyValidator: 
      externalSecret: true 
    proxyInjector:
      externalSecret: true
    profileValidator:
      externalSecret: true 
  valuesFrom:
    # identity trust anchor certificate (shared accross clusters)
  - kind: Secret
    name: linkerd-trust-anchor
    valuesKey: tls.crt
    targetPath: identityTrustAnchorsPEM

    # webhooks trust CA certificate
  - kind: Secret
    name: webhook-issuer-tls
    valuesKey: tls.crt
    targetPath: policyValidator.caBundle
  - kind: Secret
    name: webhook-issuer-tls
    valuesKey: tls.crt
    targetPath: proxyInjector.caBundle
  - kind: Secret
    name: webhook-issuer-tls
    valuesKey: tls.crt
    targetPath: profileValidator.caBundle
  



