apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-jaeger-injector
  namespace: linkerd
spec:
  interval: 1m
  dependsOn:  
  - name: linkerd-control-plane
  chart:
    spec:
      chart: linkerd-jaeger
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 1m
      reconcileStrategy: Revision
  values:
    jaeger:
      enabled: false
    webhook: 
      externalSecret: true
      injectCaFrom: webhook-issuer-tls
    collector:
      # one of the shortcomming of helm is that you are limited 
      # by custom ways of passing values
      config: |
        receivers:
          otlp:
            protocols:
              grpc:
              http:
          opencensus:
          zipkin:
          jaeger:
            protocols:
              grpc:
              thrift_http:
              thrift_compact:
              thrift_binary:
        processors:
          batch:
        extensions:
          health_check:
        exporters:
          otlp/jaeger:
            endpoint: jaeger-collector.wac-hospital:4317
            tls:
              insecure: true
        service:
          extensions: [health_check]
          pipelines:
            traces:
              receivers: [otlp,opencensus,zipkin,jaeger]
              processors: [batch]
              exporters: ["otlp/jaeger"]
  # valuesFrom:
  # - kind: Secret
  #   name: webhook-issuer-tls
  #   valuesKey: tls.crt
  #   targetPath: webhook.caBundle
  

