apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-jaeger-injector
  namespace: linkerd
spec:
  interval: 1m
  dependsOn:  
  - name: linkerd-control-plane
  chart:
    spec:
      chart: linkerd-jaeger
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 1m
      reconcileStrategy: Revision
  values:
    jaeger:
      enabled: false
  valuesFrom:
  - kind: Secret
    name: webhook-issuer-tls
    valuesKey: tls.crt
    targetPath: webhook.caBundle
  - kind: ConfigMap
    name: collector-config-value
    valuesKey: collector-config
    targetPath: collector.config


