apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd

resources:
- namespace.yaml
- helm-repository.yaml
- crds.helm-release.yaml
- control-plane.helm-release.yaml
# - jaeger-injector.helm-release.yaml


 